### ISSUE TITLE
Modern Flyouts not working on Windows 24H2.

### ISSUE THREAD

**Issue by anubhavongit** [decimaldreamer/Modern-Flyouts-24H2#1]
![Screenshot (5)](https://github.com/user-attachments/assets/84d6624d-ccb8-4069-8509-d2b00fa86946)

It doesn't get installed on Windows 24H2
![Screenshot (5)](https://github.com/user-attachments/assets/2dab214c-4fbe-4eae-9c85-95c0f6c3e33d)

**Comment by 0x1-1** [comment]
Hello,

You need to install the .cert file before proceeding with the installation.

The file: https://github.com/decimaldreamer/Modern-Flyouts-24H2/releases/download/0.9.8515.0/ModernFlyouts.Package_0.9.8515.0_x86_x64.cer

Once you download the certificate, please follow these steps: Local Machine > Place in the following store > Browse > Trusted Root Certification Authorities > Finish

Thank you.
