### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by turninto** [decimaldreamer/Modern-Flyouts-24H2#2]
Probably due to user error, so I apologize if I sound dumb, but I can't seem to proceed to the actual installation because Windows insists the certificates are unverified.

![image](https://github.com/user-attachments/assets/220edf54-3714-4a13-aa64-afe7974bb16d)

I've installed the certificate provided with the current release, but it hasn't made a difference. I'm wondering if there's another step I've missed.

Thank you.

**Comment by 0x1-1** [comment]
Hello, did you try put the cert to Trusted Root Certification Authorities?
